name: graded
description: Track and manage your school grades with ease
publish_to: "none"
version: 2.6.4+252

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  animations: ^2.0.0
  collection: ^1.16.0
  device_info_plus: ^9.0.0
  diacritic: ^0.1.0
  dynamic_color: ^1.4.0
  flex_color_picker: ^3.3.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_file_dialog: ^3.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.0
  intl: ^0.18.0
  package_info_plus: ^5.0.1
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  showcaseview: ^2.0.0
  sliver_tools: ^0.2.0
  url_launcher: ^6.0.0

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_native_splash: ^2.2.0
  icons_launcher: ^2.1.0
  import_sorter: ^4.6.0
  lint: ^2.0.0
  test: ^1.22.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
    - family: notosans
      fonts:
        - asset: assets/fonts/notosans/NotoSans-Regular.ttf
        - asset: assets/fonts/notosans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/notosans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/notosans/NotoSans-Black.ttf
          weight: 900
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
    - family: sfpro
      fonts:
        - asset: assets/fonts/sfpro/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/sfpro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/sfpro/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/sfpro/SF-Pro-Display-Black.otf
          weight: 900
  assets:
    - assets/class_data/lux/
    - assets/illustrations/

flutter_intl:
  enabled: true
  class_name: TranslationsClass
  main_locale: en_GB
  arb_dir: lib/localization/l10n
  output_dir: lib/localization/generated

icons_launcher:
  image_path: "assets/icons/icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icons/icon-roundrect.png"
      adaptive_foreground_image: "assets/icons/icon-adaptive-foreground.png"
      adaptive_background_color: "#62A9E1"
      adaptive_monochrome_image: "assets/icons/icon-adaptive-monochrome.png"
    ios:
      enable: true
      image_path: "assets/icons/icon.png"
    web:
      enable: true
      image_path: "assets/icons/icon-roundrect.png"
      favicon_path: "assets/icons/icon-roundrect.png"

flutter_native_splash:
  color: "#FDFCFF"
  color_dark: "#1A1C1E"
  image: assets/icons/icon-roundrect.png
  android_12:
    color: "#FDFCFF"
    color_dark: "#1A1C1E"
    image: assets/icons/icon-adaptive-foreground.png
    icon_background_color: "#62A9E1"
  android: true
  ios: true
  web: true

import_sorter:
  ignored_files:
    - \/lib\\localization\\.*
    - \/lib\\ui\\utilities\\custom_icons.dart
